'use client';

import { ArrowRight, BadgeCheck, BriefcaseBusiness, Check, ChevronRight, Clock3, Languages, Mail, MapPin, MessageCircleMore, Smartphone, Sparkles, Users } from 'lucide-react';
import { useSite } from '@/components/site-shell';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion';
import { assetPath } from '@/lib/site-paths';
import { content } from '@/lib/home-content';
import { pageContent, type PageId } from '@/lib/page-content';
import { serviceDetails, serviceImages, serviceSlugs } from '@/lib/service-details';

function useCopy() {
  const site = useSite();
  return { ...site, s: (fr: string, ht: string) => site.lang === 'fr' ? fr : ht, t: content[site.lang] };
}

export function Breadcrumb({ title, service = false }: { title: string; service?: boolean }) {
  const { s, href } = useCopy();
  return <nav className="breadcrumb" aria-label={s('Fil d’Ariane', 'Chemen paj la')}><a href={href('/')}>{s('Accueil', 'Akèy')}</a><ChevronRight size={14} aria-hidden="true" />{service && <><a href={href('/services/')}>{s('Services', 'Sèvis')}</a><ChevronRight size={14} aria-hidden="true" /></>}<span aria-current="page">{title}</span></nav>;
}

function PageHero({ page }: { page: PageId }) {
  const { lang, s } = useCopy();
  const [label, title, description] = pageContent[page][lang];
  return <div className={`inner-hero hero-${page}`}><div className="page-width"><Breadcrumb title={label} /><div className="inner-hero-copy"><span className="section-kicker">{label}</span><h1>{title}</h1><p>{description}</p>{page === 'application' && <span className="launch-label"><Clock3 size={16} />{s('Application en préparation', 'Aplikasyon an ap prepare')}</span>}</div></div></div>;
}

export function PageCTA({ provider = false }: { provider?: boolean }) {
  const { s, href } = useCopy();
  return <section className="page-cta page-width"><div><span className="section-kicker light">Ti Sèvis · Ayiti</span><h2>{provider ? s('Votre prochaine opportunité commence ici.', 'Pwochen opòtinite w la kòmanse isit la.') : s('Un coup de main, bientôt à portée de main.', 'Yon kout men ap disponib byento.')}</h2><p>{s('L’application est en préparation. Découvrez le projet et échangez avec notre équipe.', 'Aplikasyon an ap prepare. Dekouvri pwojè a epi pale ak ekip nou an.')}</p></div><a className="button button-light" href={href('/contact/')}>{s('Nous contacter', 'Kontakte nou')}<ArrowRight size={18} /></a></section>;
}

function ServicesPage() {
  const { t, s, href } = useCopy();
  return <><section className="page-width page-section catalog-section"><div className="catalog-note"><Sparkles size={21} /><p>{s('Les catégories donnent des idées. Votre besoin définit le service.', 'Kategori yo bay lide. Se bezwen w ki defini sèvis la.')}</p><span>{s('À découvrir dans l’app', 'Pou dekouvri nan app la')}</span></div><div className="catalog-grid">{t.services.map(([title, description], i) => <a className="catalog-card" href={href(`/services/${serviceSlugs[i]}/`)} key={title}><div className="catalog-image"><img src={assetPath(serviceImages[i])} alt={title} loading={i < 2 ? 'eager' : 'lazy'} /><span className="catalog-index">0{i + 1}</span></div><div className="catalog-card-copy"><h2>{title}</h2><p>{description}</p><span className="text-link">{s('Découvrir ce service', 'Dekouvri sèvis sa a')}<ArrowRight size={18} /></span></div></a>)}</div></section><section className="page-width language-banner"><Languages size={34} /><div><h2>{s('Le service commence par se comprendre.', 'Bon sèvis kòmanse lè nou konprann youn lòt.')}</h2><p>{s('Anglais, espagnol, créole ou français : nos prestataires premium vous accompagnent selon les langues indiquées sur leur profil.', 'Anglè, panyòl, kreyòl oswa franse : founisè sèvis premium nou yo ap ede w selon lang ki sou pwofil yo.')}</p></div></section><PageCTA /></>;
}

function HowPage() {
  const { t, s, href } = useCopy();
  const tips = [
    [s('Le service et le résultat attendu', 'Sèvis la ak rezilta ou vle a'), s('Le lieu, la date et votre budget', 'Kote a, dat la ak bidjè w'), s('Les détails qui feront la différence', 'Detay ki ap fè diferans lan')],
    [s('Les compétences et les langues du profil', 'Konpetans ak lang ki sou pwofil la'), s('Les propositions et les avis disponibles', 'Pwopozisyon ak sa kliyan yo di'), s('Un périmètre et un prix convenus ensemble', 'Sa travay la gen ladan l ak pri nou dakò sou li')],
    [s('Les échanges avec votre prestataire', 'Mesaj ak moun k ap ba w sèvis la'), s('La confirmation des étapes du service', 'Konfimasyon etap sèvis la'), s('Votre retour une fois le travail terminé', 'Sa ou panse apre travay la fini')],
  ];
  return <><section className="page-width page-section process-list">{t.steps.map(([title, description], i) => <article className="process-row" key={title}><div className="process-photo"><img src={assetPath(['/step-publier.png', '/step-choisir.png', '/step-suivre.png'][i])} alt={title} loading={i === 0 ? 'eager' : 'lazy'} /><span>0{i + 1}</span></div><div className="process-copy"><span className="section-kicker">{s('Dans l’application', 'Nan aplikasyon an')} · 0{i + 1}</span><h2>{title}</h2><p>{description}</p><ul className="check-list">{tips[i].map(tip => <li key={tip}><Check size={18} />{tip}</li>)}</ul></div></article>)}</section><aside className="page-width quiet-note"><Smartphone size={23} /><p>{s('Ce site vous présente le parcours. La publication de demandes et la gestion des services seront disponibles dans l’application au lancement.', 'Sit sa a prezante kijan sa pral mache. W ap kapab pibliye demann ak jere sèvis yo nan aplikasyon an lè li lanse.')}</p><a className="text-link" href={href('/application/')}>{t.app}<ArrowRight size={17} /></a></aside><PageCTA /></>;
}

function MissionPage() {
  const { t, s, href } = useCopy();
  return <><section className="page-width page-section editorial-split"><div className="editorial-photo"><img src={assetPath('/service-personnalise.png')} alt={s('Une communauté de professionnels réunie autour d’une cliente', 'Yon kominote pwofesyonèl ansanm ak yon kliyan')} /><span>{s('Les talents de chez nous.', 'Talan moun lakay.')}</span></div><div className="editorial-copy"><span className="section-kicker warm">{s('Notre raison d’être', 'Poukisa nou la')}</span><h2>{t.missionTitle}</h2><p>{t.missionText}</p><p>{s('Nous croyons qu’un service bien rendu fait plus que cocher une tâche : il libère du temps, crée une relation et ouvre une opportunité.', 'Nou kwè yon sèvis ki byen fèt fè plis pase fini yon travay : li bay tan, li kreye yon relasyon epi li louvri yon opòtinite.')}</p><blockquote>« {t.missionQuote} »</blockquote></div></section><section className="mission-values"><div className="page-width"><div className="section-heading"><span className="section-kicker warm">{s('Ce qui nous guide', 'Sa ki gide nou')}</span><h2>{s('L’humain au cœur du service.', 'Moun nan kè sèvis la.')}</h2></div><div className="principle-grid">{[[s('La proximité', 'Pwoksimite'), s('Relier les besoins aux savoir-faire présents dans les quartiers et les communautés.', 'Konekte bezwen yo ak konpetans ki nan katye ak kominote yo.')], [s('Le respect', 'Respè'), s('Reconnaître la valeur du travail et encourager des échanges clairs, de part et d’autre.', 'Rekonèt valè travay epi ankouraje bon kominikasyon ant moun yo.')], [s('Les opportunités', 'Opòtinite'), s('Aider les professionnels à être visibles et les familles à trouver la bonne personne.', 'Ede pwofesyonèl yo jwenn vizibilite epi ede fanmi yo jwenn bon moun nan.')]].map(([title, text], i) => <article key={title}><span>0{i + 1}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section><section className="page-width page-section two-audiences"><article><Users size={30} /><h2>{s('Pour les familles et les particuliers', 'Pou fanmi ak moun yo')}</h2><p>{s('Moins de temps à chercher. Plus de choix pour les services qui comptent au quotidien.', 'Mwens tan ap chèche. Plis chwa pou sèvis ki enpòtan chak jou yo.')}</p><a className="text-link" href={href('/services/')}>{s('Explorer les services', 'Gade sèvis yo')}<ArrowRight size={18} /></a></article><article><BriefcaseBusiness size={30} /><h2>{s('Pour les talents et les professionnels', 'Pou talan ak pwofesyonèl yo')}</h2><p>{s('Un espace pour présenter vos compétences et bâtir votre réputation, service après service.', 'Yon espas pou prezante konpetans ou epi bati repitasyon w, sèvis apre sèvis.')}</p><a className="text-link" href={href('/prestataires/')}>{s('Découvrir le parcours prestataire', 'Dekouvri chemen pou ofri sèvis')}<ArrowRight size={18} /></a></article></section><PageCTA /></>;
}

const departments = [['Ouest', 'Lwès'], ['Sud-Est', 'Sidès'], ['Nord', 'Nò'], ['Nord-Est', 'Nòdès'], ['Artibonite', 'Latibonit'], ['Centre', 'Sant'], ['Sud', 'Sid'], ['Grande-Anse', 'Grandans'], ['Nord-Ouest', 'Nòdwès'], ['Nippes', 'Nip']];

function ZonesPage() {
  const { s, href } = useCopy();
  return <><section className="page-width page-section"><div className="coverage-banner"><div><span className="section-kicker light">{s('Une vision nationale', 'Yon vizyon nasyonal')}</span><h2>{s('Du Nord au Sud, les talents sont partout.', 'Soti nan Nò rive nan Sid, talan yo toupatou.')}</h2><p>{s('Ti Sèvis porte un projet pour les dix départements d’Haïti. Les ouvertures se feront progressivement, selon les services et les prestataires disponibles.', 'Ti Sèvis se yon pwojè pou tout dis depatman peyi a. Sèvis yo ap louvri piti piti, selon kalite sèvis ak moun ki disponib yo.')}</p></div><div className="coverage-number"><strong>10</strong><span>{s('départements · une communauté', 'depatman · yon kominote')}</span></div></div><div className="department-grid">{departments.map(([fr, ht], i) => <article className="department-card" key={fr}><span>{String(i + 1).padStart(2, '0')}</span><MapPin size={22} /><h2>{s(fr, ht)}</h2><p>{s('Déploiement prévu', 'Deplwaman prevwa')}</p></article>)}</div><p className="source-note">{s('Référentiel des départements :', 'Lis depatman yo :')} <a href="https://www.ihsi.gouv.ht/statistiques/statistiques_demographiques_et_sociales/projections_et_estimations_de_la_population" target="_blank" rel="noreferrer">IHSI</a></p></section><section className="page-width rollout-note"><Clock3 size={30} /><div><h2>{s('Quand Ti Sèvis arrivera-t-il chez vous ?', 'Kilè Ti Sèvis ap rive nan zòn ou ?')}</h2><p>{s('Le calendrier et les zones effectivement ouvertes seront annoncés au lancement. Indiquez votre commune dans votre message pour nous faire connaître votre intérêt.', 'N ap anonse kalandriye a ak zòn ki louvri yo lè lansman an fèt. Mete komin ou nan mesaj ou pou fè nou konnen ou enterese.')}</p><a className="text-link" href={href('/contact/')}>{s('Nous écrire à propos de ma zone', 'Ekri nou sou zòn mwen an')}<ArrowRight size={18} /></a></div></section><PageCTA /></>;
}

function FaqPage() {
  const { t, s, href } = useCopy();
  const groups = [
    { id: 'projet', title: s('Le projet & le lancement', 'Pwojè a ak lansman an'), items: [t.faqs[0], [s('Quand l’application sera-t-elle disponible ?', 'Kilè aplikasyon an ap disponib ?'), s('L’application est en préparation. La date de lancement et les liens officiels de téléchargement seront communiqués lorsqu’ils seront disponibles.', 'Aplikasyon an ap prepare. N ap bay dat lansman an ak lyen ofisyèl pou telechaje yo lè yo disponib.')], [s('Les dix départements sont-ils déjà ouverts ?', 'Èske tout dis depatman yo deja louvri ?'), s('Le projet a une ambition nationale. La disponibilité des services sera progressive et annoncée au lancement.', 'Pwojè a gen yon vizyon pou tout peyi a. Sèvis yo ap disponib piti piti, epi n ap bay detay yo nan lansman an.')]] },
    { id: 'services', title: s('Les services & l’application', 'Sèvis yo ak aplikasyon an'), items: [t.faqs[2], [s('Les catégories affichées limitent-elles les demandes ?', 'Èske demann yo limite ak kategori ki sou sit la ?'), s('Non. Elles illustrent des besoins courants. Vous pourrez aussi décrire une demande personnalisée dans la future application.', 'Non. Yo se egzanp bezwen moun genyen souvan. W ap kapab dekri bezwen pa w nan aplikasyon an tou.')], [s('Comment les prix seront-ils définis ?', 'Kijan pri yo pral fikse ?'), s('Vous préciserez votre besoin et votre budget. Le périmètre du service et son prix devront être convenus avec le prestataire avant confirmation. Les modalités détaillées seront précisées au lancement.', 'W ap esplike bezwen w ak bidjè w. Ou menm ak moun k ap bay sèvis la dwe dakò sou travay la ak pri a anvan konfimasyon. N ap bay plis detay nan lansman an.')], [s('Puis-je organiser une aide pour un proche ?', 'Èske mwen ka òganize èd pou yon moun pa m ?'), s('Le projet prévoit de permettre des demandes pour un proche, avec son accord et les informations utiles pour le service. Le fonctionnement précis sera présenté dans l’application.', 'Pwojè a prevwa demann pou yon moun pa w, avèk konsantman li ak enfòmasyon ki itil pou sèvis la. Detay yo ap nan aplikasyon an.')]] },
    { id: 'prestataires', title: s('Les prestataires & les langues', 'Moun k ap bay sèvis yo ak lang yo'), items: [t.faqs[3], t.faqs[5], [s('Dans quelles langues pourrai-je être accompagné ?', 'Nan ki lang mwen ka jwenn èd ?'), s('L’interface est pensée en français et en créole. L’accompagnement premium prévoit des prestataires parlant anglais, espagnol, créole ou français, selon leur profil et leur disponibilité.', 'Entèfas la fèt an franse ak kreyòl. Sèvis premium la prevwa moun ki pale anglè, panyòl, kreyòl oswa franse, selon pwofil ak disponibilite yo.')], [s('Que signifie l’accompagnement premium ?', 'Kisa akonpayman premium vle di ?'), s('Il met notamment en avant la possibilité d’échanger dans votre langue avec un prestataire adapté. Les conditions de cette offre seront communiquées au lancement.', 'Li mete aksan sitou sou posiblite pou pale nan lang ou ak yon moun ki adapte ak bezwen w. N ap bay kondisyon òf sa a nan lansman an.')]] },
  ];
  return <><section className="page-width page-section faq-layout"><aside className="faq-sidebar"><span className="section-kicker">{s('Vos questions', 'Kesyon w yo')}</span>{groups.map(group => <a href={`#${group.id}`} key={group.id}>{group.title}<ArrowRight size={15} /></a>)}<div><MessageCircleMore size={27} /><h2>{s('Une autre question ?', 'Yon lòt kesyon ?')}</h2><a className="text-link" href={href('/contact/')}>{s('Parlons-en', 'Ann pale')}<ArrowRight size={17} /></a></div></aside><div className="faq-groups">{groups.map(group => <section id={group.id} key={group.id}><h2>{group.title}</h2><Accordion className="detail-faq">{group.items.map(([question, answer]) => <AccordionItem key={question} value={question}><AccordionTrigger>{question}</AccordionTrigger><AccordionContent><p>{answer}</p></AccordionContent></AccordionItem>)}</Accordion></section>)}</div></section><PageCTA /></>;
}

function ApplicationPage() {
  const { t, s, href } = useCopy();
  return <><section className="page-width page-section application-preview"><div className="app-preview-top"><span>{s('Aperçu du projet', 'Apèsi pwojè a')}</span><span>Ti Sèvis · iOS & Android</span></div><img src={assetPath('/ti-sevis-app.jpeg')} alt={s('Maquettes de l’application Ti Sèvis : accueil, services et profils', 'Modèl aplikasyon Ti Sèvis : akèy, sèvis ak pwofil')} /><p>{s('Maquettes de présentation. L’interface pourra évoluer avant le lancement.', 'Modèl pou prezante pwojè a. Entèfas la ka chanje anvan lansman an.')}</p></section><section className="page-width feature-triptych">{[[Smartphone, s('Tout au même endroit', 'Tout nan yon sèl kote'), s('Vos demandes, les propositions et les profils réunis dans une seule application.', 'Demann ou yo, pwopozisyon ak pwofil yo ansanm nan yon sèl aplikasyon.')], [MessageCircleMore, s('Des échanges plus simples', 'Kominikasyon pi fasil'), s('Un espace pour discuter du besoin, des horaires et des détails avec votre prestataire.', 'Yon espas pou pale sou bezwen an, lè yo ak detay yo ak moun k ap ba w sèvis la.')], [BadgeCheck, s('Votre choix, en confiance', 'Chwazi ak konfyans'), s('Des informations de profil et des avis pour vous aider à choisir la bonne personne.', 'Enfòmasyon pwofil ak sa kliyan yo di pou ede w chwazi bon moun nan.')]].map(([Icon, title, text]) => { const FeatureIcon = Icon as typeof Smartphone; return <article key={String(title)}><FeatureIcon size={27} /><h2>{String(title)}</h2><p>{String(text)}</p></article>; })}</section><section className="page-width language-banner"><Languages size={36} /><div><h2>{s('Le français et le kreyòl, naturellement.', 'Franse ak kreyòl, natirèlman.')}</h2><p>{t.appBullets[2]}. {s('Pour les services premium, retrouvez les langues d’accompagnement sur le profil de chaque prestataire.', 'Pou sèvis premium yo, gade lang chak founisè sèvis pale sou pwofil li.')}</p><a className="text-link" href={href('/fonctionnement/')}>{s('Découvrir les trois étapes', 'Dekouvri twa etap yo')}<ArrowRight size={17} /></a></div></section><PageCTA /></>;
}

function ProvidersPage() {
  const { s, href } = useCopy();
  return <><section className="page-width page-section editorial-split provider-story"><div className="editorial-copy"><span className="section-kicker warm">{s('Votre métier. Votre avenir.', 'Metye w. Avni w.')}</span><h2>{s('Vous avez le savoir-faire. Faisons-le connaître.', 'Ou gen konpetans la. Ann fè moun konnen sa.')}</h2><p>{s('Ti Sèvis se construit pour donner aux professionnels haïtiens un espace où présenter leur activité et rencontrer de nouveaux clients.', 'Ti Sèvis ap konstwi yon espas pou pwofesyonèl ayisyen prezante aktivite yo epi rankontre nouvo kliyan.')}</p><ul className="check-list"><li><Check size={18} />{s('Présentez vos compétences et vos langues', 'Prezante konpetans ou ak lang ou pale')}</li><li><Check size={18} />{s('Précisez votre zone et vos disponibilités', 'Presize zòn ou ak lè ou disponib')}</li><li><Check size={18} />{s('Construisez votre réputation au fil des services', 'Bati repitasyon w pandan w ap bay sèvis')}</li></ul><a className="button button-primary" href={href('/contact/#prestataires')}>{s('Faire connaître mon intérêt', 'Fè konnen mwen enterese')}<ArrowRight size={18} /></a></div><div className="editorial-photo"><img src={assetPath('/service-reparations.png')} alt={s('Un professionnel réalise une réparation chez une cliente', 'Yon pwofesyonèl fè yon reparasyon lakay yon kliyan')} /><span>{s('Des compétences. De vraies opportunités.', 'Konpetans. Vrè opòtinite.')}</span></div></section><section className="page-width provider-steps"><div className="section-heading"><span className="section-kicker">{s('Le parcours prévu', 'Chemen nou prevwa a')}</span><h2>{s('Préparez votre arrivée sur Ti Sèvis.', 'Prepare pou w antre nan Ti Sèvis.')}</h2></div><div className="principle-grid">{[[s('Présentez votre activité', 'Prezante aktivite w'), s('Identifiez vos services, votre expérience et les zones où vous souhaitez intervenir.', 'Idantifye sèvis ou yo, eksperyans ou ak zòn kote ou vle travay yo.')], [s('Préparez votre profil', 'Prepare pwofil ou'), s('Le parcours d’inscription prévoira des informations professionnelles et une vérification d’identité.', 'Enskripsyon an ap prevwa enfòmasyon pwofesyonèl ak yon verifikasyon idantite.')], [s('Découvrez les demandes', 'Dekouvri demann yo'), s('Au lancement, vous pourrez consulter les besoins et proposer vos services selon les conditions de la plateforme.', 'Lè li lanse, w ap kapab gade bezwen yo epi pwopoze sèvis ou selon kondisyon platfòm nan.')]].map(([title, text], i) => <article key={title}><span>0{i + 1}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section><aside className="page-width quiet-note"><Clock3 size={24} /><p>{s('Les inscriptions ne sont pas encore ouvertes. Un message à l’équipe exprime votre intérêt ; il ne crée pas de profil prestataire.', 'Enskripsyon yo poko louvri. Yon mesaj bay ekip la fè nou konnen ou enterese ; li pa kreye yon pwofil founisè sèvis.')}</p></aside><PageCTA provider /></>;
}

function ContactPage() {
  const { s, href } = useCopy();
  const subjects = [
    { id: 'lancement', Icon: Smartphone, title: s('Suivre le lancement', 'Jwenn nouvèl sou lansman an'), text: s('Faites-nous connaître votre intérêt et votre commune pour le lancement de l’application.', 'Fè nou konnen ou enterese epi bay komin ou pou lansman aplikasyon an.'), subject: 'Lancement Ti Sèvis', body: s('Bonjour,\n\nJe souhaite recevoir des informations sur le lancement de Ti Sèvis.\nMa commune : \n\nMerci.', 'Bonjou,\n\nMwen ta renmen jwenn enfòmasyon sou lansman Ti Sèvis.\nKomin mwen : \n\nMèsi.') },
    { id: 'prestataires', Icon: BriefcaseBusiness, title: s('Proposer mes services', 'Ofri sèvis mwen'), text: s('Présentez votre métier, votre zone et les langues dans lesquelles vous accompagnez vos clients.', 'Prezante metye w, zòn ou ak lang ou pale ak kliyan ou yo.'), subject: 'Devenir prestataire Ti Sèvis', body: s('Bonjour,\n\nJe souhaite proposer mes services sur Ti Sèvis.\nMon activité : \nMa zone : \nMes langues : \n\nMerci.', 'Bonjou,\n\nMwen ta renmen ofri sèvis mwen sou Ti Sèvis.\nAktivite mwen : \nZòn mwen : \nLang mwen pale : \n\nMèsi.') },
    { id: 'question', Icon: MessageCircleMore, title: s('Poser une question', 'Poze yon kesyon'), text: s('Un point à éclaircir sur le projet ou une suggestion à partager ? Nous vous lisons.', 'Ou bezwen yon detay sou pwojè a oswa ou gen yon sijesyon ? Ekri nou.'), subject: 'Question à propos de Ti Sèvis', body: s('Bonjour,\n\nMa question à propos de Ti Sèvis :\n\n', 'Bonjou,\n\nKesyon mwen sou Ti Sèvis :\n\n') },
  ];
  return <><section className="page-width page-section contact-layout"><div className="contact-intro"><span className="contact-icon"><Mail size={32} /></span><h2>{s('Un échange, ça commence simplement.', 'Yon ti pale ka kòmanse fasil.')}</h2><a className="contact-address" href="mailto:bonjour@tisevis.ht">bonjour@tisevis.ht</a><p>{s('Choisissez le sujet de votre message. Votre messagerie s’ouvrira avec un brouillon que vous pourrez compléter et envoyer.', 'Chwazi sijè mesaj ou a. App imel ou ap louvri ak yon bouyon ou ka konplete epi voye.')}</p><div className="contact-language"><Languages size={20} /><span>{s('Écrivez-nous en français ou en créole.', 'Ekri nou an franse oswa an kreyòl.')}</span></div></div><div className="contact-topics">{subjects.map(({ id, Icon, title, text, subject, body }) => <article id={id} key={id}><Icon size={24} /><div><h2>{title}</h2><p>{text}</p><a className="text-link" href={`mailto:bonjour@tisevis.ht?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`}>{s('Préparer mon e-mail', 'Prepare imel mwen')}<ArrowRight size={18} /></a></div></article>)}</div></section><aside className="page-width contact-faq"><div><h2>{s('La réponse est peut-être déjà ici.', 'Repons lan ka deja isit la.')}</h2><p>{s('Consultez les questions sur les services, les prestataires et la future application.', 'Gade kesyon sou sèvis yo, founisè sèvis yo ak aplikasyon k ap vini an.')}</p></div><a className="button button-secondary" href={href('/faq/')}>{s('Voir la FAQ', 'Gade kesyon yo')}<ArrowRight size={18} /></a></aside></>;
}

export default function SitePage({ page }: { page: PageId }) {
  const Page = { services: ServicesPage, fonctionnement: HowPage, mission: MissionPage, zones: ZonesPage, faq: FaqPage, application: ApplicationPage, prestataires: ProvidersPage, contact: ContactPage }[page];
  return <div className="inner-page"><PageHero page={page} /><Page /></div>;
}

export function ServiceDetailPage({ index }: { index: number }) {
  const { lang, t, s, href } = useCopy();
  const detail = serviceDetails[lang][index];
  const title = t.services[index][0];
  return <div className="inner-page service-detail"><div className="page-width"><Breadcrumb title={title} service /></div><section className="page-width service-detail-hero"><div><a className="section-kicker" href={href('/services/')}>{s('Nos services', 'Sèvis nou yo')}</a><h1>{detail.headline}</h1><p>{detail.intro}</p><a className="button button-primary" href={href('/application/')}><Smartphone size={18} />{s('Découvrir la future application', 'Dekouvri aplikasyon k ap vini an')}</a><span className="service-availability"><Clock3 size={16} />{s('Réservation dans l’app au lancement', 'Rezèvasyon nan app la lè li lanse')}</span></div><img src={assetPath(serviceImages[index])} alt={title} /></section><section className="page-width page-section service-detail-body"><div><span className="section-kicker">{title}</span><h2>{s('Un coup de main, concrètement.', 'Yon kout men, toutbon.')}</h2><div className="service-examples">{detail.examples.map((example, i) => <div key={example}><span>0{i + 1}</span><h3>{example}</h3></div>)}</div><p className="detail-note">{detail.note}</p></div><aside className="prepare-card"><BadgeCheck size={28} /><h2>{s('Pour bien préparer votre demande', 'Pou byen prepare demann ou')}</h2><ul className="check-list">{detail.prepare.map(item => <li key={item}><Check size={18} />{item}</li>)}</ul><a className="text-link" href={href('/fonctionnement/')}>{s('Comment ça marche', 'Kijan sa mache')}<ArrowRight size={18} /></a></aside></section><section className="page-width related-services"><div className="section-heading"><span className="section-kicker">{s('Et pour le reste ?', 'E pou rès la ?')}</span><h2>{s('D’autres façons de vous aider.', 'Lòt fason pou ede w.')}</h2></div><div>{[(index + 1) % 8, (index + 2) % 8].map(i => <a key={i} href={href(`/services/${serviceSlugs[i]}/`)}><img src={assetPath(serviceImages[i])} alt="" loading="lazy" /><span>{t.services[i][0]}</span><ArrowRight size={20} /></a>)}</div></section><PageCTA /></div>;
}
