export type Lang = 'fr' | 'ht';

export const content = {
  fr: {
    nav: ['Services', 'Comment ça marche', 'Zones', 'Notre mission', 'FAQ'],
    app: 'Découvrir l’app',
    menu: 'Ouvrir le menu',
    eyebrow: 'Le coup de main qui change tout',
    heroA: 'Un petit service.',
    heroB: 'Une grande différence.',
    heroText: 'Ti Sèvis vous met en relation avec des prestataires de confiance pour les besoins du quotidien — simplement, rapidement, partout où la vie vous appelle.',
    seeServices: 'Voir les services',
    trust: ['Prestataires vérifiés', 'Service 100 % local', 'Prix transparents'],
    provider: 'Prestataires qualifiés',
    nearby: 'proches de chez vous',
    request: 'Demande publiée',
    realtime: 'Réponses en temps réel',
    introTag: 'Conçu pour le quotidien haïtien',
    introTitle: 'Moins de courses. Plus de temps pour l’essentiel.',
    introText: 'Une seule application pour trouver la bonne personne, publier votre besoin et suivre votre service sans complication.',
    serviceTag: 'Services',
    serviceTitle: 'De quoi avez-vous besoin aujourd’hui ?',
    serviceText: 'Des petits besoins ponctuels aux services récurrents, Ti Sèvis rapproche les talents locaux des personnes qui en ont besoin.',
    services: [
      ['Ménage & lessive', 'Nettoyage, repassage et soin du linge à domicile.'],
      ['Courses & livraison', 'Achats, repas, médicaments et petits colis.'],
      ['Beauté à domicile', 'Coiffure, tissage, maquillage et soins personnels.'],
      ['Cuisine & événements', 'Cuisine à domicile et aide pour vos petites réceptions.'],
      ['Maison & réparations', 'Petits travaux, peinture, montage et dépannage.'],
      ['Assistance quotidienne', 'Files d’attente, documents, accompagnement et commissions.'],
      ['Services professionnels', 'Soutien administratif, numérique et besoins ponctuels.'],
      ['Votre besoin', 'Décrivez votre demande : la communauté Ti Sèvis répond.'],
    ],
    allInApp: 'Tous les services seront réservés et gérés dans l’application.',
    howTag: 'Comment ça marche',
    howTitle: 'Demandez. Choisissez. Soufflez.',
    howText: 'Ti Sèvis rend la recherche d’aide aussi simple qu’un message.',
    steps: [
      ['Publiez votre besoin', 'Décrivez le service, le lieu, la date et votre budget dans l’application.'],
      ['Choisissez en confiance', 'Comparez les profils, les avis et les propositions des prestataires.'],
      ['Suivez votre service', 'Échangez, confirmez et gérez votre demande au même endroit.'],
    ],
    whyTag: 'Pourquoi Ti Sèvis',
    whyTitle: 'La confiance avant tout.',
    whyText: 'Une expérience pensée autour de la proximité, de la transparence et de la dignité du travail.',
    values: [
      ['Identités vérifiées', 'Des profils contrôlés pour bâtir une communauté plus sûre.'],
      ['Choix transparent', 'Vous voyez les informations utiles avant de vous engager.'],
      ['Conversation directe', 'Discutez des détails avec le prestataire dans l’application.'],
      ['Talents valorisés', 'Une vitrine numérique pour les savoir-faire de chez nous.'],
    ],
    missionTag: 'Notre mission',
    missionTitle: 'Faire circuler les opportunités, quartier par quartier.',
    missionText: 'Ti Sèvis veut simplifier la vie des familles tout en donnant aux prestataires haïtiens un moyen moderne de trouver des clients, de bâtir leur réputation et de développer leur activité.',
    missionQuote: 'Chwazi nou se rann tèt ou yon gwo sèvis.',
    zonesTag: '1 pays · 10 départements',
    zonesTitle: 'Une ambition nationale, quartier par quartier.',
    zonesText: 'Ti Sèvis est pensé pour servir les dix départements d’Haïti. Le déploiement commencera progressivement, selon les services et les prestataires disponibles.',
    availableSoon: 'Déploiement progressif',
    notify: 'Être prévenu au lancement',
    appTag: 'L’application Ti Sèvis',
    appTitle: 'Tous vos services. Une seule app.',
    appText: 'Publiez une demande, recevez des propositions, discutez avec un prestataire et suivez chaque étape depuis votre téléphone.',
    appBullets: ['Profils et services au même endroit', 'Demandes et réponses en temps réel', 'Interface en français et en kreyòl'],
    faqTag: 'Questions fréquentes',
    faqTitle: 'Tout ce qu’il faut savoir avant le lancement.',
    faqs: [
      ['Qu’est-ce que Ti Sèvis ?', 'Ti Sèvis est une plateforme mobile qui met en relation les personnes ayant un besoin du quotidien avec des prestataires locaux qualifiés.'],
      ['Peut-on déjà réserver un service ?', 'Pas encore. Nous préparons le lancement pilote de l’application dans le Grand Port-au-Prince. Vous pouvez rejoindre la liste d’information dès maintenant.'],
      ['Le site permet-il de réserver ?', 'Non. Ce site présente le projet. Les demandes, propositions, échanges et suivis seront centralisés dans l’application Ti Sèvis.'],
      ['Comment les prestataires seront-ils vérifiés ?', 'Le parcours d’inscription prévoira une vérification d’identité et des informations professionnelles avant l’activation du profil.'],
      ['Dans quelles langues l’application sera-t-elle disponible ?', 'L’expérience est pensée en français et en kreyòl afin d’être accessible au plus grand nombre.'],
      ['Comment devenir prestataire Ti Sèvis ?', 'Une campagne d’inscription dédiée sera ouverte avant le lancement. Laissez-nous un message pour être parmi les premiers informés.'],
    ],
    finalTitle: 'Le quotidien devient plus léger avec Ti Sèvis.',
    finalText: 'Soyez parmi les premiers à découvrir une nouvelle façon de trouver et proposer des services en Haïti.',
    join: 'Rejoindre la liste de lancement',
    footerLine: 'Le petit service qui simplifie votre quotidien.',
    project: 'Projet',
    users: 'Pour les utilisateurs',
    providers: 'Pour les prestataires',
    legal: '© 2026 Ti Sèvis. Tous droits réservés.',
    made: 'Pensé et construit pour Haïti.',
  },
  ht: {
    nav: ['Sèvis', 'Kijan sa mache', 'Zòn sèvis yo', 'Misyon nou', 'Kesyon moun poze souvan'],
    app: 'Dekouvri aplikasyon an',
    menu: 'Ouvri meni an',
    eyebrow: 'Ti kout men ki chanje tout bagay',
    heroA: 'Yon ti sèvis.',
    heroB: 'Yon gwo diferans.',
    heroText: 'Ti Sèvis mete w an kontak ak moun k ap bay sèvis ou ka fè konfyans pou bezwen chak jou — fasil, rapid, nenpòt kote lavi mennen w.',
    seeServices: 'Gade sèvis yo',
    trust: ['Founisè sèvis verifye', 'Sèvis 100 % lokal', 'Pri ki klè'],
    provider: 'Founisè sèvis kalifye',
    nearby: 'toupre lakay ou',
    request: 'Demann pibliye',
    realtime: 'Repons an tan reyèl',
    introTag: 'Fèt pou lavi chak jou ann Ayiti',
    introTitle: 'Mwens kouri. Plis tan pou sa ki enpòtan.',
    introText: 'Yon sèl aplikasyon pou jwenn bon moun nan, pibliye bezwen w epi swiv sèvis ou san tèt chaje.',
    serviceTag: 'Sèvis',
    serviceTitle: 'Ki sèvis ou bezwen jodi a?',
    serviceText: 'Soti nan ti bezwen rapid rive nan sèvis regilye, Ti Sèvis konekte talan lokal ak moun ki bezwen yo.',
    services: [
      ['Netwayaj & lesiv', 'Netwayaj, repase ak swen rad lakay ou.'],
      ['Komisyon & livrezon', 'Acha, manje, medikaman ak ti pakè.'],
      ['Bote lakay', 'Kwafè, tise, makiyaj ak swen pèsonèl.'],
      ['Manje & evènman', 'Kwit manje lakay ak asistans pou ti resepsyon.'],
      ['Kay & reparasyon', 'Ti travay, penti, montaj ak depanaj.'],
      ['Asistans chak jou', 'Kanpe nan liy, dokiman, akonpayman ak komisyon.'],
      ['Sèvis pwofesyonèl', 'Sipò administratif, dijital ak bezwen espesyal.'],
      ['Bezwen pa w', 'Dekri sa w bezwen : kominote Ti Sèvis la ap reponn.'],
    ],
    allInApp: 'Tout sèvis yo ap rezève epi jere nan aplikasyon an.',
    howTag: 'Kijan li mache',
    howTitle: 'Mande. Chwazi. Pran souf.',
    howText: 'Ti Sèvis fè chèche èd vin fasil tankou voye yon mesaj.',
    steps: [
      ['Pibliye bezwen w', 'Dekri sèvis la, kote a, dat la ak bidjè w nan aplikasyon an.'],
      ['Chwazi ak konfyans', 'Konpare pwofil, sa kliyan yo di ak pwopozisyon founisè sèvis yo.'],
      ['Swiv sèvis la', 'Pale, konfime epi jere demann ou nan yon sèl kote.'],
    ],
    whyTag: 'Poukisa Ti Sèvis',
    whyTitle: 'Konfyans anvan tout bagay.',
    whyText: 'Yon eksperyans ki chita sou pwoksimite, transparans ak respè pou travay.',
    values: [
      ['Idantite verifye', 'Pwofil ki kontwole pou bati yon kominote ki pi an sekirite.'],
      ['Chwa ki klè', 'Ou wè enfòmasyon itil yo anvan ou pran desizyon.'],
      ['Pale dirèkteman', 'Diskite detay yo ak founisè sèvis la nan aplikasyon an.'],
      ['Talan jwenn valè', 'Yon vitrin dijital pou konesans ak konpetans moun lakay.'],
    ],
    missionTag: 'Misyon nou',
    missionTitle: 'Fè opòtinite sikile, katye pa katye.',
    missionText: 'Ti Sèvis vle rann lavi fanmi yo pi fasil epi bay founisè sèvis ayisyen yon zouti modèn pou jwenn kliyan, bati repitasyon yo ak devlope aktivite yo.',
    missionQuote: 'Chwazi nou se rann tèt ou yon gwo sèvis.',
    zonesTag: '1 peyi · 10 depatman',
    zonesTitle: 'Yon vizyon nasyonal, katye pa katye.',
    zonesText: 'Ti Sèvis fèt pou sèvi tout dis depatman Ayiti. N ap deplwaye l piti piti, selon sèvis ak founisè sèvis ki disponib yo.',
    availableSoon: 'Deplwaman piti piti',
    notify: 'Fè m konnen lè li lanse',
    appTag: 'Aplikasyon Ti Sèvis',
    appTitle: 'Tout sèvis ou yo. Yon sèl app.',
    appText: 'Pibliye yon demann, resevwa pwopozisyon, pale ak yon founisè sèvis epi swiv chak etap sou telefòn ou.',
    appBullets: ['Pwofil ak sèvis nan yon sèl kote', 'Demann ak repons an tan reyèl', 'Entèfas an franse ak kreyòl'],
    faqTag: 'Kesyon moun poze souvan',
    faqTitle: 'Tout sa pou w konnen anvan lansman an.',
    faqs: [
      ['Kisa Ti Sèvis ye?', 'Ti Sèvis se yon platfòm mobil ki konekte moun ki gen bezwen chak jou ak founisè sèvis lokal ki kalifye.'],
      ['Èske mwen ka rezève yon sèvis deja?', 'Poko. N ap prepare lansman aplikasyon an. Ou ka antre nan lis enfòmasyon an depi kounye a.'],
      ['Èske mwen ka rezève sou sit la?', 'Non. Sit sa a prezante pwojè a. Demann, pwopozisyon, mesaj ak swivi yo ap fèt nan aplikasyon Ti Sèvis la.'],
      ['Kijan n ap verifye founisè sèvis yo?', 'Enskripsyon an ap gen verifikasyon idantite ak enfòmasyon pwofesyonèl anvan pwofil la aktive.'],
      ['Nan ki lang aplikasyon an ap disponib?', 'Eksperyans lan fèt an franse ak kreyòl pou plis moun ka sèvi avè l.'],
      ['Kijan pou m vin yon founisè sèvis Ti Sèvis?', 'N ap louvri yon kanpay enskripsyon espesyal anvan lansman an. Voye yon mesaj pou w pami premye moun ki jwenn nouvèl la.'],
    ],
    finalTitle: 'Lavi chak jou vin pi lejè ak Ti Sèvis.',
    finalText: 'Se pou w pami premye moun ki dekouvri yon nouvo fason pou jwenn ak pwopoze sèvis ann Ayiti.',
    join: 'Antre nan lis lansman an',
    footerLine: 'Ti sèvis ki rann lavi chak jou pi fasil.',
    project: 'Pwojè',
    users: 'Pou itilizatè yo',
    providers: 'Pou founisè sèvis yo',
    legal: '© 2026 Ti Sèvis. Tout dwa rezève.',
    made: 'Panse epi bati pou Ayiti.',
  },
};
