export const serviceSlugs = ['menage-lessive', 'courses-livraison', 'beaute', 'cuisine-evenements', 'maison-reparations', 'assistance', 'professionnels', 'sur-mesure'];
export const serviceImages = ['/service-menage.png', '/service-livraison.png', '/service-beaute.png', '/service-cuisine.png', '/service-reparations.png', '/service-assistance.png', '/service-professionnels.png', '/service-personnalise.png'];

export const serviceDetails = {
  fr: [
    { headline: 'Une maison fraîche. Du temps pour vous.', intro: 'Confiez les tâches de la maison à une personne dont vous aurez choisi le profil. Un besoin ponctuel ou une aide régulière : décrivez ce qui compte pour vous.', examples: ['Nettoyage des pièces et des surfaces', 'Lessive, repassage et pliage du linge', 'Remise en ordre avant ou après une réception'], prepare: ['Le nombre de pièces et les surfaces à entretenir', 'Les produits et le matériel disponibles', 'Vos horaires et les consignes pour le linge'], note: 'Précisez les produits à éviter et les objets fragiles avant l’intervention.' },
    { headline: 'Vos courses avancent. Votre journée aussi.', intro: 'Des achats du quotidien au petit colis à déposer, trouvez un coup de main pour les trajets que vous ne pouvez pas faire vous-même.', examples: ['Courses au marché ou en magasin', 'Récupération de repas et de petits colis', 'Dépôt de documents et achats de proximité'], prepare: ['La liste des achats ou le contenu du colis', 'Les lieux de récupération et de livraison', 'Le budget des achats et la plage horaire'], note: 'Le coût des achats et la rémunération du prestataire seront à distinguer dans votre demande.' },
    { headline: 'Prenez soin de vous, chez vous.', intro: 'Faites de votre rendez-vous beauté un moment qui s’adapte à votre quotidien. Présentez vos envies pour trouver le savoir-faire qui vous correspond.', examples: ['Coiffure, tresses et tissage', 'Maquillage pour une occasion', 'Soins esthétiques non médicaux'], prepare: ['Le style ou le résultat souhaité', 'Les produits ou accessoires à prévoir', 'La durée disponible et le lieu du rendez-vous'], note: 'Discutez des produits utilisés et signalez toute sensibilité connue au prestataire.' },
    { headline: 'Recevez vos proches. Profitez du moment.', intro: 'Un repas à préparer, des invités à accueillir ou une table à installer : trouvez une aide adaptée à la taille de votre réception.', examples: ['Préparation de repas à domicile', 'Aide à la mise en place et au service', 'Rangement après une petite réception'], prepare: ['Le nombre de personnes et le menu souhaité', 'Les ingrédients et équipements disponibles', 'Les horaires, préférences et allergies alimentaires'], note: 'Convenez à l’avance de la répartition des achats et de la préparation.' },
    { headline: 'Les petits travaux ne doivent plus attendre.', intro: 'Donnez une nouvelle place à une étagère ou un nouveau souffle à une pièce. Décrivez votre projet pour être mis en relation avec un professionnel adapté.', examples: ['Montage de meubles et pose d’étagères', 'Petits travaux de peinture', 'Entretien et réparations selon les compétences du professionnel'], prepare: ['Une description précise et, si utile, des photos', 'Les dimensions et le matériel déjà disponible', 'Les contraintes d’accès et votre calendrier'], note: 'Les interventions spécialisées nécessitent des compétences adaptées. Clarifiez le périmètre avant de confirmer.' },
    { headline: 'Un coup de main pour les petites choses.', intro: 'Certaines journées ont besoin d’une personne en plus. Ti Sèvis prévoit de faciliter les commissions et l’accompagnement du quotidien.', examples: ['Aide pour des commissions et des documents', 'Accompagnement à un rendez-vous', 'Assistance pratique pour un proche'], prepare: ['Les étapes de la commission ou du rendez-vous', 'Les horaires et les déplacements prévus', 'Les besoins d’accompagnement et les autorisations utiles'], note: 'L’accompagnement présenté ici est une aide pratique, sans prise en charge médicale.' },
    { headline: 'Faites avancer votre activité.', intro: 'Pour une tâche administrative ou un besoin numérique ponctuel, trouvez une compétence complémentaire et gardez votre attention sur votre métier.', examples: ['Saisie, classement et mise en forme de documents', 'Aide à l’utilisation d’outils numériques', 'Appui ponctuel à l’organisation d’une activité'], prepare: ['Le livrable attendu et son format', 'Le délai et les informations nécessaires', 'Les modalités de travail à distance ou sur place'], note: 'Partagez uniquement les informations nécessaires à la réalisation de la tâche.' },
    { headline: 'Votre besoin ne rentre pas dans une case ?', intro: 'Les catégories sont un point de départ. Expliquez simplement l’aide dont vous avez besoin : une demande personnalisée permettra aux bons profils de se reconnaître.', examples: ['Combiner plusieurs petites tâches', 'Trouver une aide pour une occasion particulière', 'Décrire un besoin qui ne figure pas dans le catalogue'], prepare: ['Le résultat que vous voulez obtenir', 'Le lieu, la date et la durée estimée', 'Votre budget et les compétences recherchées'], note: 'La faisabilité dépendra du besoin, des compétences et de la disponibilité des prestataires.' },
  ],
  ht: [
    { headline: 'Yon kay pwòp. Plis tan pou ou.', intro: 'Chwazi moun ki pral ede w ak travay nan kay la. Kit se yon sèl fwa oswa regilyèman, esplike sa ki enpòtan pou ou.', examples: ['Netwaye chanm ak sifas yo', 'Lave, repase epi pliye rad', 'Mete kay la annòd anvan oswa apre yon resepsyon'], prepare: ['Kantite chanm ak sifas pou netwaye', 'Pwodui ak materyèl ki disponib', 'Lè ou disponib ak konsiy pou rad yo'], note: 'Di ki pwodui pou evite epi montre objè ki frajil yo anvan travay la.' },
    { headline: 'Komisyon w fèt. Jounen w avanse.', intro: 'Soti nan acha chak jou rive nan ti pakè pou depoze, jwenn yon moun pou ede w ak deplasman ou pa ka fè yo.', examples: ['Acha nan mache oswa nan magazen', 'Al chèche manje ak ti pakè', 'Depoze dokiman ak fè acha toupre'], prepare: ['Lis acha yo oswa sa ki nan pakè a', 'Kote pou pran ak kote pou livre', 'Bidjè pou acha yo ak lè ou bezwen sèvis la'], note: 'Separe lajan acha yo ak pri sèvis moun k ap ede w la nan demann nan.' },
    { headline: 'Pran swen tèt ou, lakay ou.', intro: 'Chwazi yon randevou bote ki mache ak jounen w. Esplike sa ou vle pou jwenn konpetans ki koresponn ak bezwen w.', examples: ['Kwafè, tres ak tise', 'Makiyaj pou yon okazyon', 'Swen bote ki pa swen medikal'], prepare: ['Stil oswa rezilta ou vle a', 'Pwodui ak akseswa pou prepare', 'Tan ou disponib ak kote randevou a ap fèt'], note: 'Pale sou pwodui yo pral itilize yo epi fè moun nan konnen si po w sansib.' },
    { headline: 'Resevwa moun pa w. Pwofite moman an.', intro: 'Yon manje pou prepare, envite pou resevwa oswa tab pou ranje : jwenn èd ki mache ak gwosè resepsyon w lan.', examples: ['Prepare manje lakay', 'Ede mete bagay yo anplas ak sèvi manje', 'Ranje apre yon ti resepsyon'], prepare: ['Kantite moun ak meni ou vle a', 'Engredyan ak ekipman ki disponib', 'Lè, preferans ak alèji manje yo'], note: 'Mete nou dakò davans sou kiyès k ap fè acha yo ak prepare manje a.' },
    { headline: 'Ti travay yo pa bezwen tann ankò.', intro: 'Mete yon etajè anplas oswa bay yon chanm yon lòt aparans. Dekri pwojè w pou jwenn yon pwofesyonèl ki gen bon konpetans yo.', examples: ['Monte mèb ak poze etajè', 'Ti travay penti', 'Antretyen ak reparasyon selon konpetans pwofesyonèl la'], prepare: ['Yon deskripsyon klè ak foto si sa itil', 'Mezi yo ak materyèl ki deja disponib', 'Kondisyon pou antre ak dat ou vle a'], note: 'Travay espesyalize mande konpetans ki adapte. Mete nou dakò sou sa travay la gen ladan l.' },
    { headline: 'Yon kout men pou ti bagay yo.', intro: 'Gen jou ou bezwen yon moun anplis. Ti Sèvis ap fasilite komisyon ak akonpayman nan lavi chak jou.', examples: ['Èd pou komisyon ak dokiman', 'Akonpayman nan yon randevou', 'Asistans pratik pou yon moun pa w'], prepare: ['Etap komisyon an oswa randevou a', 'Lè yo ak deplasman pou fè yo', 'Bezwen akonpayman ak otorizasyon ki nesesè'], note: 'Akonpayman sa a se yon èd pratik. Li pa yon sèvis medikal.' },
    { headline: 'Fè aktivite w avanse.', intro: 'Pou yon travay administratif oswa yon bezwen dijital, jwenn yon lòt konpetans pou w ka konsantre sou metye w.', examples: ['Antre done, klase ak mete dokiman anfòm', 'Èd pou sèvi ak zouti dijital', 'Sipò pou òganize yon aktivite'], prepare: ['Rezilta ak fòma ou vle a', 'Dat limit ak enfòmasyon ki nesesè', 'Si travay la ap fèt adistans oswa sou plas'], note: 'Pataje sèlman enfòmasyon ki nesesè pou fè travay la.' },
    { headline: 'Ou pa jwenn kategori pou bezwen w lan ?', intro: 'Kategori yo se yon pwen depa. Esplike èd ou bezwen an pou moun ki gen bon konpetans yo ka reponn.', examples: ['Mete plizyè ti travay ansanm', 'Jwenn èd pou yon okazyon espesyal', 'Dekri yon bezwen ki pa nan lis la'], prepare: ['Rezilta ou vle jwenn nan', 'Kote, dat ak kantite tan ou panse sa ap pran', 'Bidjè w ak konpetans w ap chèche'], note: 'Sa ki posib ap depann de bezwen an, konpetans yo ak disponibilite moun k ap bay sèvis yo.' },
  ],
};
